# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-22 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0002_spell_tweeted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=20),
        ),
    ]
