# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_appearance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
