# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-20 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_player_first_appearance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_appearance',
            new_name='debut',
        ),
    ]
