# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_auto_20170829_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='aka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
